'use strict';

var German = (function(originalDic){
  let germanLexicon = {
    "merry":"fröhlich",
    "christmas":"weihnachten",
    "and":"und",
    "happy":"frohes",
    "new":"neues",
    "year":"Jahr",
    "hello":"hallo",
    "i":"ich",
    "the":"das",
    "is":"ist",
    "not":"nicht",
    "yes":"ja",
    "you":"du",
    "so":"so",
    "she":"sie",
    "we":"wir",
    "what":"was",
    "still":"noch",
    "with":"with",
    "reindeer":"rentier",
    "rudolph":"rudolph",
    "red":"rot",
    "nose":"nase",
    "tree":"baum",
    "jinglebell":"klingglöckchen",
    "snow":"schnee",
    "snowman":"schneemann",
    "winter":"winter",
    "joy":"freude",
    "wish":"wunsch",
    "a":"ein",
    "good":"gut",
    "tidings":"botschaft",
    "who":"wer",
    "whoever":"wer auch immer",
    "are":"sind",
    "for":"zum",
    "had":"hätten",
    "very":"sehr",
    "shiny":"glänzend",
    "if":"ob",
    "ever":"je",
    "saw":"sah",
    "him":"ihm",
    "would":"würde",
    "even":"sogar",
    "say":"sagen",
    "it":"es",
    "glows":"leuchtet",
    "all":"alle",
    "of":"von",
    "other":"andere",
    "used":"gewöhnt",
    "laugh":"lachen",
    "call":"anruf",
    "names":"namen",
    "they":"sie",
    "never":"nie",
    "let":"lassen",
    "poor":"arm",
    "play":"spielen",
    "in":"im",
    "any":"irgendein",
    "games":"spiele",
    "woman":"frau",
    "man":"mann",
    "holiday":"ferien"
  }

  originalDic.getGerman = function(userInput){
    return germanLexicon
  };
})(Dictionary || {});
